name: "Test"
on: push
jobs:

  build_env:
    name: Build Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check if env was changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            env:
              - 'env/**'
              - '.github/**'
      - name: Build Environment
        uses: docker/build-push-action@v1
        if: steps.changes.outputs.env == 'true'
        with:
          path: ./env
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
          registry: ghcr.io
          repository: "arrowresearch/qc0/env/${{ github.ref }}"
          tags: latest
          push: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [build_env]
    container:
      image: "ghcr.io/arrowresearch/qc0/env/${{ github.ref }}"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Start PostgreSQL
        run: service postgresql start
      - name: Init database
        run: psql -1 -f ./db.sql
      - name: Install dependencies
        run: poetry install
      - name: Run formatting checks
        run: make fmt
      - name: Run linter checks
        run: make lint
      - name: Run tests
        run: make test-cov
