name: "Test"
on: push
jobs:

  build_env:
    name: Build Environment
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Check if env was changed
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            env:
              - 'env/**'
      - name: Build Environment
        uses: docker/build-push-action@v1
        if: steps.changes.outputs.env == 'true'
        with:
          path: ./env
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: arrowresearch/qc0/env
          tags: latest
          push: true

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [build_env]

    steps:
      - name: Docker login
        run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run tests
        run: |
          docker run \
            -v "${PWD}:${PWD}" -w "${PWD}" \
            docker.pkg.github.com/arrowresearch/qc0/env:latest \
            make ci-test
